
### Task begin
@hostname = http://localhost:3000/

{{hostname}}tasks
###

GET {{hostname}}tasks?status=DONE&search=ea
###

POST {{hostname}}tasks
Content-Type: application/json

{
    "title": "Laragon",
    "description": "Crea entornos de desarrollo"
}
###

GET {{hostname}}tasks/133
###

DELETE {{hostname}}tasks/8
###

PATCH {{hostname}}tasks/2/status
Content-Type: application/json

{
    "status": "done"
}
### Task end

### Authentication begin
POST {{hostname}}auth/signup
Content-Type: application/json

{
    "username": "orlando",
    "password": "123456"
}