@hostname = http://localhost:3000/

{{hostname}}tasks
###

GET {{hostname}}tasks?status=DOsNE&search=
###

POST {{hostname}}tasks
Content-Type: application/json

{
    "title": "Laragon",
    "description": "Crea entornos de desarrollo"
}
###

GET {{hostname}}tasks/133
###

DELETE {{hostname}}tasks/8
###

PATCH {{hostname}}tasks/54528070-0dfe-11ec-80a1-4da13d28adce/status
Content-Type: application/json

{
    "status": "invali"
}